name: senior_client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900